export const COLOR_INPUT_FIELD_GRADIENT_PERCENT = 35;
export const COLOR_PICKER_COLOR_CHANGE_DELAY_MS = 100;
export const TILES_COLOR_BLACK = "#292F33";
export const TILES_COLOR_WHITE = "#F1F3F4";

export const MATCHING_PATTERNS = [
  [8, 9, 10],
  [11, 12, 13, 14, 15],
];

export const PRESET_DATA_INDEX_LOCAL_STORAGE_KEY = "truchettiles-preset-data-index";
export const PRESET_DATA_LIST = [
  {
    pattern: "12",
    primaryColor: "#4FAEDE",
    secondaryColor: "#4FDEB8",
    strokeColor: "#4F59DE",
    strokeSize: "72",
    tileSize: "36",
  },
  {
    pattern: "1",
    primaryColor: "#20BFFE",
    secondaryColor: "#8B20FE",
    strokeColor: "#FEE420",
    strokeSize: "95",
    tileSize: "40",
  },
  {
    pattern: "7",
    primaryColor: "#267CB5",
    secondaryColor: "#4EA2d9",
    strokeColor: "#8DC3E7",
    strokeSize: "85",
    tileSize: "75",
  },
  {
    pattern: "9",
    primaryColor: "#AFEEEE",
    secondaryColor: "#40E0D0",
    strokeColor: "#000000",
    strokeSize: "75",
    tileSize: "25",
  },
  {
    pattern: "2",
    primaryColor: "#4682B4",
    secondaryColor: "#8FBC8F",
    strokeColor: "#000000",
    strokeSize: "80",
    tileSize: "60",
  },
  {
    pattern: "15",
    primaryColor: "#DF535E",
    secondaryColor: "#EB939B",
    strokeColor: "#F7D4D7",
    strokeSize: "100",
    tileSize: "44",
  },
];

export const HTML_COLORS = [
  { name: "MediumVioletRed", hex: "#C71585" },
  { name: "DeepPink", hex: "#FF1493" },
  { name: "PaleVioletRed", hex: "#DB7093" },
  { name: "HotPink", hex: "#FF69B4" },
  { name: "LightPink", hex: "#FFB6C1" },
  { name: "Pink", hex: "#FFC0CB" },
  { name: "DarkRed", hex: "#8B0000" },
  { name: "Red", hex: "#FF0000" },
  { name: "Firebrick", hex: "#B22222" },
  { name: "Crimson", hex: "#DC143C" },
  { name: "IndianRed", hex: "#CD5C5C" },
  { name: "LightCoral", hex: "#F08080" },
  { name: "Salmon", hex: "#FA8072" },
  { name: "DarkSalmon", hex: "#E9967A" },
  { name: "LightSalmon", hex: "#FFA07A" },
  { name: "OrangeRed", hex: "#FF4500" },
  { name: "Tomato", hex: "#FF6347" },
  { name: "DarkOrange", hex: "#FF8C00" },
  { name: "Coral", hex: "#FF7F50" },
  { name: "Orange", hex: "#FFA500" },
  { name: "DarkKhaki", hex: "#BDB76B" },
  { name: "Gold", hex: "#FFD700" },
  { name: "Khaki", hex: "#F0E68C" },
  { name: "PeachPuff", hex: "#FFDAB9" },
  { name: "Yellow", hex: "#FFFF00" },
  { name: "PaleGoldenrod", hex: "#EEE8AA" },
  { name: "Moccasin", hex: "#FFE4B5" },
  { name: "PapayaWhip", hex: "#FFEFD5" },
  { name: "LightGoldenrodYellow", hex: "#FAFAD2" },
  { name: "LemonChiffon", hex: "#FFFACD" },
  { name: "LightYellow", hex: "#FFFFE0" },
  { name: "Maroon", hex: "#800000" },
  { name: "Brown", hex: "#A52A2A" },
  { name: "SaddleBrown", hex: "#8B4513" },
  { name: "Sienna", hex: "#A0522D" },
  { name: "Chocolate", hex: "#D2691E" },
  { name: "DarkGoldenrod", hex: "#B8860B" },
  { name: "Peru", hex: "#CD853F" },
  { name: "RosyBrown", hex: "#BC8F8F" },
  { name: "Goldenrod", hex: "#DAA520" },
  { name: "SandyBrown", hex: "#F4A460" },
  { name: "Tan", hex: "#D2B48C" },
  { name: "Burlywood", hex: "#DEB887" },
  { name: "Wheat", hex: "#F5DEB3" },
  { name: "NavajoWhite", hex: "#FFDEAD" },
  { name: "Bisque", hex: "#FFE4C4" },
  { name: "BlanchedAlmond", hex: "#FFEBCD" },
  { name: "Cornsilk", hex: "#FFF8DC" },
  { name: "Indigo", hex: "#4B0082" },
  { name: "RebeccaPurple", hex: "#663399" },
  { name: "Purple", hex: "#800080" },
  { name: "DarkMagenta", hex: "#8B008B" },
  { name: "DarkViolet", hex: "#9400D3" },
  { name: "DarkSlateBlue", hex: "#483D8B" },
  { name: "BlueViolet", hex: "#8A2BE2" },
  { name: "DarkOrchid", hex: "#9932CC" },
  { name: "Magenta", hex: "#FF00FF" },
  { name: "SlateBlue", hex: "#6A5ACD" },
  { name: "MediumSlateBlue", hex: "#7B68EE" },
  { name: "MediumOrchid", hex: "#BA55D3" },
  { name: "MediumPurple", hex: "#9370DB" },
  { name: "Orchid", hex: "#DA70D6" },
  { name: "Violet", hex: "#EE82EE" },
  { name: "Plum", hex: "#DDA0DD" },
  { name: "Thistle", hex: "#D8BFD8" },
  { name: "Lavender", hex: "#E6E6FA" },
  { name: "MidnightBlue", hex: "#191970" },
  { name: "Navy", hex: "#000080" },
  { name: "DarkBlue", hex: "#00008B" },
  { name: "MediumBlue", hex: "#0000CD" },
  { name: "Blue", hex: "#0000FF" },
  { name: "RoyalBlue", hex: "#4169E1" },
  { name: "SteelBlue", hex: "#4682B4" },
  { name: "DodgerBlue", hex: "#1E90FF" },
  { name: "DeepSkyBlue", hex: "#00BFFF" },
  { name: "CornflowerBlue", hex: "#6495ED" },
  { name: "SkyBlue", hex: "#87CEEB" },
  { name: "LightSkyBlue", hex: "#87CEFA" },
  { name: "LightSteelBlue", hex: "#B0C4DE" },
  { name: "LightBlue", hex: "#ADD8E6" },
  { name: "PowderBlue", hex: "#B0E0E6" },
  { name: "Teal", hex: "#008080" },
  { name: "DarkCyan", hex: "#008B8B" },
  { name: "LightSeaGreen", hex: "#20B2AA" },
  { name: "CadetBlue", hex: "#5F9EA0" },
  { name: "DarkTurquoise", hex: "#00CED1" },
  { name: "MediumTurquoise", hex: "#48D1CC" },
  { name: "Turquoise", hex: "#40E0D0" },
  { name: "Cyan", hex: "#00FFFF" },
  { name: "Aquamarine", hex: "#7FFFD4" },
  { name: "PaleTurquoise", hex: "#AFEEEE" },
  { name: "LightCyan", hex: "#E0FFFF" },
  { name: "DarkSlateGray", hex: "#2F4F4F" },
  { name: "DarkGreen", hex: "#006400" },
  { name: "Green", hex: "#008000" },
  { name: "DarkOliveGreen", hex: "#556B2F" },
  { name: "ForestGreen", hex: "#228B22" },
  { name: "SeaGreen", hex: "#2E8B57" },
  { name: "Olive", hex: "#808000" },
  { name: "OliveDrab", hex: "#6B8E23" },
  { name: "MediumSeaGreen", hex: "#3CB371" },
  { name: "LimeGreen", hex: "#32CD32" },
  { name: "Lime", hex: "#00FF00" },
  { name: "SpringGreen", hex: "#00FF7F" },
  { name: "MediumSpringGreen", hex: "#00FA9A" },
  { name: "DarkSeaGreen", hex: "#8FBC8F" },
  { name: "MediumAquamarine", hex: "#66CDAA" },
  { name: "YellowGreen", hex: "#9ACD32" },
  { name: "LawnGreen", hex: "#7CFC00" },
  { name: "Chartreuse", hex: "#7FFF00" },
  { name: "LightGreen", hex: "#90EE90" },
  { name: "GreenYellow", hex: "#ADFF2F" },
  { name: "PaleGreen", hex: "#98FB98" },
  { name: "MistyRose", hex: "#FFE4E1" },
  { name: "AntiqueWhite", hex: "#FAEBD7" },
  { name: "Linen", hex: "#FAF0E6" },
  { name: "Beige", hex: "#F5F5DC" },
  { name: "WhiteSmoke", hex: "#F5F5F5" },
  { name: "LavenderBlush", hex: "#FFF0F5" },
  { name: "OldLace", hex: "#FDF5E6" },
  { name: "AliceBlue", hex: "#F0F8FF" },
  { name: "Seashell", hex: "#FFF5EE" },
  { name: "GhostWhite", hex: "#F8F8FF" },
  { name: "Honeydew", hex: "#F0FFF0" },
  { name: "FloralWhite", hex: "#FFFAF0" },
  { name: "Azure", hex: "#F0FFFF" },
  { name: "MintCream", hex: "#F5FFFA" },
  { name: "Snow", hex: "#FFFAFA" },
  { name: "Ivory", hex: "#FFFFF0" },
  { name: "Gainsboro", hex: "#DCDCDC" },
  { name: "LightGray", hex: "#D3D3D3" },
  { name: "Silver", hex: "#C0C0C0" },
  { name: "DarkGray", hex: "#A9A9A9" },
  { name: "Gray", hex: "#808080" },
  { name: "DimGray", hex: "#696969" },
  { name: "SlateGray", hex: "#708090" },
  { name: "LightSlateGray", hex: "#778899" },
  { name: "Black", hex: "#000000" },
  { name: "White", hex: "#FFFFFF" },
];
